vJSCC_DB['ClassList']['TemplateEngine'] = {
    "JSCC_type": "CLASS",
    "JSCC_init_date": "24.1.2018",
    "JSCC_mod_date": "2018/01/24 10:44:59",
    "tClassname": "TemplateEngine",
    "tSuperClassname": "",
    "sClassType": "Default",
    "tAuthor": "Engelbert Niehaus",
    "tEMail": "niehaus@uni-landau.de",
    "tAttributes": "",
    "tMethods": "section(pData:Hash):String\nurl(pData:Hash):String\ntable(pData:Hash):String\nmath(pData:Hash):String\nhorizontal_line(pData:Hash):String\nimages(pData:Hash):String\ninline_elements(pData:Hash):String\ntoc(pData:Hash):String\ninit(pTplHash:Hash)",
    "sAttribList": "",
    "tAttribName": "",
    "tAttribType": "",
    "tAttribComment": "",
    "tAttribDefault": "",
    "sAttribTypeList": "",
    "tMethodHeader": "init(pTplHash:Hash)",
    "tMethodName": "",
    "tMethodComment": "what does section_gen do?",
    "sMethodList": "init",
    "tMethodCode": "",
    "tLoopObject": "pTplHash",
    "tLoopMethod": ")",
    "AttribType": {},
    "AttribAccess": {},
    "AttribDefault": {},
    "AttribComment": {},
    "MethodParameter": {
        "section": "pData:Hash",
        "url": "pData:Hash",
        "table": "pData:Hash",
        "math": "pData:Hash",
        "horizontal_line": "pData:Hash",
        "images": "pData:Hash",
        "inline_elements": "pData:Hash",
        "toc": "pData:Hash",
        "init": "pTplHash:Hash"
    },
    "MethodReturn": {
        "section": "String",
        "url": "String",
        "table": "String",
        "math": "String",
        "horizontal_line": "String",
        "images": "String",
        "inline_elements": "String",
        "toc": "String",
        "init": ""
    },
    "MethodCode": {
        "section": "",
        "url": "",
        "table": "",
        "math": "",
        "horizontal_line": "",
        "images": "",
        "inline_elements": "",
        "toc": "",
        "init": "// Code for init\nthis.aTplHash = pTplHash;\n\nfor (var vKey in pTplHash) {\n  if (pTplHash.hasOwnProperty(vKey)) {\n    // with vKey = \"sections\" the replacement can be called vTplEngine.sections(pContextHash)\n    this[vKey] = Handlebars.compile(pTplHash[vKey]);\n  }\n};\n"
    },
    "MethodComment": {
        "section": "Comment for section",
        "url": "Comment for url",
        "table": "Comment for table",
        "math": "Comment for math",
        "horizontal_line": "Comment for horizontal_line",
        "images": "Comment for images",
        "inline_elements": "Comment for inline_elements",
        "toc": "Comment for toc",
        "init": "Init the template engine with a template hash. And create the replace functions of the Class TemplateEngine dynamically.\nOverwrite the defined methods like 'sections(pData)'"
    },
    "MethodAccess": {
        "section": "public",
        "url": "public",
        "table": "public",
        "math": "public",
        "horizontal_line": "public",
        "images": "public",
        "inline_elements": "public",
        "toc": "public",
        "init": "public"
    },
    "sClassList": "TemplateEngine",
    "tMethodAccess": "public",
    "JSCC_version": "1"
}